Repository IS4301-DevOps/notional-app, pull requests merged in 2022-10, with the labels that each got.

#31 Added loading page
  components/common/Loading.tsx
  package-lock.json
  package.json
  pages/index.tsx
  yarn.lock
Labels: enhancement

#33 feat: Add Tip of The Day
  components/landing/TipCard.tsx
  pages/index.tsx
Labels: enhancement

#41 40 change data type of carbontarget from decimal to integer
  components/landing/DashboardCard.tsx
  prisma/schema.prisma
Labels: bug

#46 38 add goal setting page
  lib/clientApi.ts
  pages/api/users/[id]/[target].ts
  pages/dashboard/setGoal.tsx
Labels: enhancement

#56 22 add notifications panel
  components/common/Notifications.tsx
  components/landing/NotificationButton.tsx
  components/layout/Layout.tsx
  pages/dashboard/set-goal.tsx
Labels: enhancement

#59 feat: added top 3 rankings for leaderboard
  components/leaderboard/LeaderboardTopRankings.jsx
  components/leaderboard/LeaderboardVerticalCard.tsx
  package-lock.json
  package.json
  pages/leaderboard/index.tsx
  yarn.lock
Labels: enhancement

#37 Update CarouselCard.tsx
  components/landing/CarouselCard.tsx
Labels: bug

#60 15 design and add icons for quick links in landing page
  components/landing/ActionPanel.tsx
Labels: enhancement

#65 64 remove transactions icon from landing page
  components/common/Loading.tsx
  components/landing/ActionPanel.tsx
  components/layout/Layout.tsx
Labels: bug

#87 feat: add month carousel
  components/dashboard/MonthCarousel.tsx
  components/landing/CarouselCard.tsx
  components/layout/DashboardLayout.tsx
  components/recommend/SearchBar.tsx
  hooks/dashboard.ts
  pages/index.tsx
  pages/recommend/index.tsx
Labels: enhancement

#89 Created cashback and carbon information
  components/layout/DashboardLayout.tsx
  pages/dashboard/set-goal.tsx
Labels: enhancement

#100 Fixed width for ratings bar and added details for Animal sub section …
  components/quiz/RecommendationDetails.tsx
Labels: bug, enhancement

#101 Leaderboard Modal, Leaderboard Enhancements
  components/leaderboard/BadgesCollection.tsx
  components/leaderboard/LeaderboardList.tsx
  components/leaderboard/LeaderboardPastWinners.tsx
  pages/leaderboard/badges-collection.tsx
  pages/leaderboard/index.tsx
Labels: enhancement

#98 Cashback > Rewards, and positive carbon > negative carbon
  components/landing/ActionPanel.tsx
  pages/dashboard/set-goal.tsx
Labels: bug

#107 90 develop article page
  components/landing/Carousel.tsx
  components/landing/CarouselCard.tsx
  hooks/queries.ts
  lib/clientApi.ts
  lib/server/post.ts
  pages/api/post/all.ts
  pages/api/post/index.ts
  pages/article/index.tsx
Labels: enhancement

#108 102 clean up mobile menu
  components/common/NavMenu.tsx
  components/layout/Layout.tsx
Labels: bug

#114 Bug fixes and info modal
  components/common/PointsContainer.tsx
  components/landing/NotificationButton.tsx
  components/layout/DashboardInfoModal.tsx
  components/layout/InfoModal.tsx
  components/layout/InfoModalButton.tsx
  components/layout/LandingInfoModal.tsx
  components/layout/Layout.tsx
  components/layout/LeaderboardInfoModal.tsx
  components/layout/RecommendationInfoModal.tsx
  components/layout/TwoFeatureContent.tsx
  components/quiz/QuizOption.tsx
  components/quiz/Steps.tsx
  constants/dashboardinfomodal.tsx
  constants/leaderboardinfomodal.tsx
  constants/recommendationinfomodal.tsx
  pages/quiz/index.tsx
  pages/quiz/quiz-questions.tsx
  public/common/tree-icon.svg
  public/infomodal/averages.svg
  public/infomodal/globe.svg
  public/infomodal/laggards.svg
  public/infomodal/leaders.svg
  public/infomodal/transaction.svg
  public/landing/dashboard-image.svg
  public/landing/esg-info-2-no-bg.svg
  public/landing/esg-info.svg
  public/landing/leaderboard-image.svg
  public/landing/recommendation-image.svg
  public/landing/track-transaction-image.svg
  styles/components/common/PointsContainer.module.css
  styles/components/layout/DashboardInfoModal.module.css
  styles/components/layout/InfoModal.module.css
  styles/components/layout/LandingInfoModal.module.css
  styles/components/layout/Layout.module.css
  styles/components/layout/LeaderboardInfoModal.module.css
  styles/components/layout/RecommendationInfoModal.module.css
  styles/components/quiz/QuizPage.module.css
Labels: bug, enhancement

#117 Set-Goal page: Change carbon from positive to negative
  pages/api/tip/today.ts
  pages/goal/set-goal/index.tsx
Labels: bug

#115 Added foundation for unit testing with Jest and React Testing Library
  components/__tests__/BadgesCollection.test.tsx
  components/__tests__/__snapshots__/BadgesCollection.test.tsx.snap
  jest.config.js
  jest.setup.js
  lib/clientApi.ts
  package-lock.json
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#119 ESG Knowledge Quiz
  components/knowledge/Core.jsx
  components/knowledge/Locale.tsx
  components/knowledge/Quiz.jsx
  components/knowledge/core-components/Explanation.jsx
  components/knowledge/core-components/InstantFeedback.jsx
  components/knowledge/core-components/QuizResultFilter.jsx
  components/knowledge/core-components/helpers.js
  components/knowledge/knowledge-quiz.tsx
  components/knowledge/quiz_styles.css
  components/landing/ESGQuiz.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/esg-quiz/index.tsx
  pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#124 Refactored recommendation 'quiz' to 'survey'
  components/layout/InfoModal.tsx
  components/layout/LandingInfoModal.tsx
  components/recommend/SurveyCard.tsx
  components/survey/InformationRow.tsx
  components/survey/NextButton.tsx
  components/survey/PreviousButton.tsx
  components/survey/RecommendationCard.tsx
  components/survey/RecommendationCardList.tsx
  components/survey/RecommendationDetails.tsx
  components/survey/RecommendationSurveyContainer.tsx
  components/survey/RecommendationSurveyHeader.tsx
  components/survey/Steps.tsx
  components/survey/SurveyButton.tsx
  components/survey/SurveyOption.tsx
  constants/index.tsx
  constants/notifications.tsx
  constants/survey.tsx
  pages/recommend/index.tsx
  pages/survey/index.tsx
  pages/survey/recommendations.tsx
  pages/survey/survey-brief.tsx
  pages/survey/survey-questions.tsx
  pages/survey/view-recommendation.tsx
  public/survey/green_robot.svg
  public/survey/questions_brief.svg
  public/survey/recommended_brief.svg
  public/survey/time_brief.svg
  styles/components/survey/InformationRow.module.css
  styles/components/survey/RecommendationSurveyContainer.module.css
  styles/components/survey/RecommendationSurveyHeader.module.css
  styles/components/survey/Steps.module.css
  styles/components/survey/SurveyButton.module.css
  styles/components/survey/SurveyOption.module.css
  styles/components/survey/SurveyPage.module.css
  styles/pages/survey/Survey.module.css
Labels: bug
